### ISSUE TITLE
create solution 3

### ISSUE THREAD

**Issue by SebAnghel23** [COS420-Fall24/TeamB#10]
Repetition is the key when learning something new. This goes the same for learning how to code or how to program. Creating a system within our app that requires the user to do a little bit of practice each day would create a cycle of learning. Even if it is only 10 minutes a day. The importance here is repetition, also known as long term learning. An example of this would be the app Duolingo. Where one can learn different languages through the use of short everyday practice. I believe a solution to helping computer science students hone their skills and learn is to incorporate a short everyday repetition practice.

**Comment by Jakob-Sholler** [comment]
better Description This task is to compare what we are doing with our app with things that already exist that do something similar.  I.e Our interactive textbook,
