### ISSUE TITLE
Update User Story Document

### ISSUE THREAD

**Issue by acetone01** [COS420-Fall24/TeamB#26]

**Comment by Jakob-Sholler** [comment]
Updated User story document ( /5) 

Based on the comments from deliverable 0.

If the comments were not addressed, the document will be marked as 0.

If the comments are partially addressed, the document will be marked as 2.5.

You must document a changelog by replying to the Google document comments when you think an issue has been addressed. You must also reply to comments saying what you didn’t address.

**Comment by Boubacarmank** [comment]
Quality Assurance Done my Boubacar Mankirba
