### ISSUE TITLE
Update Project Description Document

### ISSUE THREAD

**Issue by acetone01** [COS420-Fall24/TeamB#27]

**Comment by Jakob-Sholler** [comment]
Updated Project Description Document ( /5)

Based on the comments from deliverable 0.

If the comments were not addressed, the document will be marked as 0.

If the comments are partially addressed, the document will be marked as 2.5.

You must document a changelog by replying to the Google document comments when you think an issue has been addressed. You must also reply to comments saying what you didn’t address.

**Comment by SebAnghel23** [comment]
I updated the project description based off the comments we were given on deliverable 0 along with little tweaks here and there, I added comments of where the issue was with short descriptions of what changed.
