### ISSUE TITLE
Product Backlog Comments

### ISSUE THREAD

**Issue by Boubacarmank** [COS420-Fall24/TeamB#84]
Product backlog and sprint backlog should match i.e. product backlog items in the sprint backlog need to have the same IDs etc. If they do not match deduct -2 points.

Make sure that all of your user stories are in the product backlog. For any missing user story deduct -1 point.

All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.

**Comment by Jakob-Sholler** [comment]
IDS match 

No missing User Stories

All Columns Filled out
